apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: multi-containers
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]
